// Code generated by hertz generator.

package main

import (
	"WatchVideo/biz/dao/db"
	"WatchVideo/pkg/cache"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	if err := db.Init(); err != nil {
		panic(err)
	}

	if err := cache.Init(); err != nil {
		panic(err)
	}
	defer cache.Close()

	register(h)
	h.Spin()
}
