// Code generated by hertz generator.

package main

import (
	handler "WatchVideo/biz/handler"
	middleware "WatchVideo/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	user := r.Group("/user")
	{
		user.POST("/register", handler.Register)
		user.POST("/login", handler.Login)
		user.GET("/info", middleware.DualTokenAuth(), handler.GetUserInfo)
		user.PUT("/avatar/upload", middleware.DualTokenAuth(), handler.UploadAvatar)
	}

	// your code ...
}
