// Code generated by hertz generator.

package main

import (
	handler "WatchVideo/biz/handler"
	middleware "WatchVideo/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	user := r.Group("/user")
	{
		user.POST("/register", handler.Register)
		user.POST("/login", handler.Login)
		user.GET("/info", middleware.DualTokenAuth(), handler.GetUserInfo)
		user.PUT("/avatar/upload", middleware.DualTokenAuth(), handler.UploadAvatar)
	}

	video := r.Group("/video")
	{
		video.POST("/publish", middleware.DualTokenAuth(), handler.PublishVideo)
		video.GET("/list", handler.VideoList)
		video.POST("/search", handler.SearchVideos)
	}

	like := r.Group("/like")
	{
		like.POST("/action", middleware.DualTokenAuth(), handler.LikeAction)
		like.GET("/list", handler.LikeList)
	}

	// your code ...
}
