// Code generated by hertz generator.

package handler

import (
	"context"

	"WatchVideo/pkg/response"

	"github.com/cloudwego/hertz/pkg/app"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	response.Success(c, map[string]interface{}{
		"status": "up",
		"ping": "pong",
	})
}
